#端口号配置
server:
  port: 8089
#数据库连接配置
spring:
  main:
    allow-circular-references: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/queue-system-pro?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456


#图片上传
web:
  uploadpath: D:/images/queue-system/  #图片上传的路径
  load-path: file:D://images/queue-system/ #图片访问、加载的路径

#jwt配置
jwt:
  #颁发者
  issuer: itmk
  #秘钥
  secret: com.itmk
  #30分钟过期
  expiration: 3000

#不需要token验证的请求，逗号分隔配置
ignore:
  url: /api/sysUser/login,/api/sysUser/getImage,/api/upload/uploadImage,/wxapi/allApi

#mybatis plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #配置mybatis plus 在更新时只更新非空和非NULL的字段
      update-strategy: not_empty

logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger- %msg%n'